# Generated by Django 5.2.14 on 2026-05-31 16:22

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('published', 'Publié')], default='draft', max_length=10)),
                ('published_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('kind', models.CharField(blank=True, help_text='Concert, performance, spectacle…', max_length=40)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('price', models.CharField(blank=True, help_text='Ex. « Entrée libre », « 8 € ».', max_length=80)),
                ('description', models.TextField(blank=True, help_text='HTML léger sanitizé (nh3).')),
                ('cover', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='media.image')),
            ],
            options={
                'ordering': ['-starts_at'],
            },
        ),
        migrations.CreateModel(
            name='EventImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_items', to='events.event')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='media.image')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='event',
            name='gallery',
            field=models.ManyToManyField(blank=True, related_name='events', through='events.EventImage', to='media.image'),
        ),
        migrations.AddConstraint(
            model_name='eventimage',
            constraint=models.UniqueConstraint(fields=('event', 'image'), name='unique_event_image'),
        ),
    ]
