# Generated by Django 5.2.14 on 2026-06-01 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_featured',
            field=models.BooleanField(default=False, help_text="Mettre à la une sur l'accueil."),
        ),
    ]
