# Generated by Django 5.2.14 on 2026-05-31 18:26

import apps.media.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='file',
            field=models.ImageField(upload_to=apps.media.models.image_upload_to),
        ),
    ]
