# Generated by Django 5.2.14 on 2026-05-31 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0002_alter_image_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='caption',
            field=models.CharField(blank=True, help_text="Légende affichée avec l'image (galerie, public).", max_length=255),
        ),
    ]
