# Generated by Django 5.2.14 on 2026-05-31 22:18

import apps.media.models
import apps.media.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0003_image_caption'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='file',
            field=models.ImageField(upload_to=apps.media.models.image_upload_to, validators=[apps.media.validators.validate_image_file]),
        ),
    ]
