# Generated by Django 5.2.14 on 2026-06-02 19:29

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_seed_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssoContent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kicker', models.CharField(max_length=80)),
                ('title', models.CharField(max_length=120)),
                ('manifesto', models.TextField()),
                ('missions_kicker', models.CharField(max_length=80)),
                ('missions_title', models.CharField(max_length=120)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CallToAction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('page', models.CharField(choices=[('home', 'Accueil'), ('asso', "L'asso")], max_length=20)),
                ('label', models.CharField(max_length=60)),
                ('url', models.CharField(max_length=200)),
                ('variant', models.CharField(choices=[('red', 'Rouge (principal)'), ('ghost', 'Contour (secondaire)')], default='red', max_length=10)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='KeyFigure',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=60)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
