# Generated by Django 5.2.14 on 2026-06-02 19:51

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_seed_asso'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactContent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kicker', models.CharField(max_length=80)),
                ('title', models.CharField(max_length=120)),
                ('intro', models.TextField()),
                ('coordinates_title', models.CharField(max_length=80)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=200)),
                ('networks_title', models.CharField(max_length=80)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=60)),
                ('url', models.URLField()),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
