# Generated by Django 5.2.14 on 2026-06-02 20:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_seed_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='homecontent',
            name='events_count',
            field=models.PositiveSmallIntegerField(default=3, validators=[django.core.validators.MaxValueValidator(12)]),
        ),
        migrations.AddField(
            model_name='homecontent',
            name='news_count',
            field=models.PositiveSmallIntegerField(default=4, validators=[django.core.validators.MaxValueValidator(12)]),
        ),
    ]
