# Generated by Django 5.2.14 on 2026-06-02 20:52

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_homecontent_events_count_homecontent_news_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='MentionsContent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kicker', models.CharField(max_length=80)),
                ('title', models.CharField(max_length=120)),
                ('editor_html', models.TextField()),
                ('hosting_html', models.TextField()),
                ('intellectual_property_html', models.TextField()),
                ('privacy_html', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
