# Generated by Django 5.2.14 on 2026-06-02 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_seed_mentions'),
    ]

    operations = [
        migrations.AddField(
            model_name='sociallink',
            name='show_in_footer',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='sociallink',
            name='show_on_page',
            field=models.BooleanField(default=True),
        ),
    ]
