# Generated by Django 5.2.14 on 2026-06-02 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_sociallink_show_in_footer_sociallink_show_on_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calltoaction',
            name='page',
            field=models.CharField(choices=[('home', 'Accueil'), ('asso', "L'asso"), ('nav', 'Menu')], max_length=20),
        ),
    ]
