# Generated by Django 5.2.14 on 2026-06-03 15:59

import apps.media.validators
import apps.pages.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0004_alter_image_file'),
        ('pages', '0012_seed_nav_adherer'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeMedia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mode', models.CharField(choices=[('off', 'Désactivé'), ('photos', 'Photos'), ('video', 'Vidéo')], default='off', max_length=10)),
                ('video_kind', models.CharField(choices=[('file', 'Fichier téléversé'), ('embed', 'Lien YouTube / Vimeo')], default='file', max_length=10)),
                ('video_file', models.FileField(blank=True, upload_to=apps.pages.models.video_upload_to, validators=[apps.media.validators.validate_video_file])),
                ('video_url', models.URLField(blank=True, help_text='Lien YouTube ou Vimeo.')),
                ('video_caption', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HomeMediaImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('home_media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_items', to='pages.homemedia')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='media.image')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='homemedia',
            name='images',
            field=models.ManyToManyField(blank=True, related_name='+', through='pages.HomeMediaImage', to='media.image'),
        ),
        migrations.AddConstraint(
            model_name='homemediaimage',
            constraint=models.UniqueConstraint(fields=('home_media', 'image'), name='unique_home_media_image'),
        ),
    ]
