# Generated by Django 5.2.14 on 2026-06-03 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0014_seed_home_media'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homemedia',
            name='video_url',
            field=models.URLField(blank=True, help_text='Lien YouTube ou Vimeo.', max_length=500),
        ),
    ]
