# Generated by Django 5.2.14 on 2026-06-03 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0015_alter_homemedia_video_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='calltoaction',
            name='target',
            field=models.CharField(choices=[('auto', 'Automatique (lien externe = nouvel onglet)'), ('blank', 'Nouvel onglet'), ('self', 'Même onglet')], default='auto', max_length=10),
        ),
    ]
